### ISSUE TITLE
Behaviors can't be removed

### ISSUE THREAD

**Issue by andymatuschak** [Khan/Prototope#17]
@may-li and I noticed today that if we set a layer's behaviors list to a list which *excludes* a previously added behavior, that behavior isn't actually removed. Looks like that logic is missing from `BehaviorDriver.updateWithLayer()`.

@saniul, would you be willing to take a look? If not, no worries at all!

**Comment by saniul** [comment]
Ah, yes, will do

**Comment by may-li** [comment]
Yay! Thank you!!

**Comment by saniul** [comment]
Weird, can’t seem to reproduce, at least naively:
```swift
        self.catLayer.behaviors = [ActionBehavior { layer in
                Layer.root.backgroundColor = Color.red
            }]
        self.catLayer.behaviors = [CollisionBehavior(with: rainbowLayer) { kind in
            switch kind {
            case .Entering:
                self.makeSparkle(self.catLayer)
            default:
                ()
            }
        }]
```
(the background never gets set to red, if you put a breakpoint in the first behavior – it never gets triggered)

@andymatuschak @may-li mind sharing a scene which exhibits this bug?

**Comment by andymatuschak** [comment]
Nope, I'm full of crap. You're right, @saniul!

@may-li, we must have been hitting a different problem! Hm hm.
