### ISSUE TITLE
console.log() stops working after end of main completes

### ISSUE THREAD

**Issue by kevinb7** [Khan/Prototope#34]
I modified the JSTest.swift to have a ```consoleLogHandler```:
```
context.consoleLogHandler = { str in
    println(str)
}
```

I also added some ```console.log``` statements at the end of JSTest.js:
```
afterDuration(1, function() {
     layer.backgroundColor = new Color({red: 0.0, green: 0.7, blue: 1.0, alpha: 0.7});
     console.log("Hello, world");
});
console.log("hello");
console.log("goodbye");

var foo = function() { console.log("foo"); };
foo();

"Done JSTest.js"
```

The resulting output was:
```
hello
goodbye
foo
Done JSTest.js
```

I was expecting ```Hello, world``` to appear after ```Done JSTest.js```.  I know that ```afterDuration``` fired the callback successfully because the layer background color changed to blue.

**Comment by kevinb7** [comment]
As a side note, it would be nice to have a default ```consoleLogHandler```.

**Comment by andymatuschak** [comment]
Interesting. I'm very surprised at that!

> As a side note, it would be nice to have a default consoleLogHandler.

Right, yes.

**Comment by kevinb7** [comment]
I'll add a ```consoleLogHandler``` because I know how to do that.

**Comment by kevinb7** [comment]
I was able to get ```console.log``` working in callbacks by changing:
```
let loggingTrampoline: @objc_block JSValue -> Void = { [weak self] value in
   self?.consoleLogHandler?(value.toString())
   return
}
```

to
```
let loggingTrampoline: @objc_block JSValue -> Void = { value in
    self.consoleLogHandler?(value.toString())
    return
}
```

I think the reason why it wasn't working was after ```makeJSLayer()``` completes, nothing is holding a strong reference to the ```context``` it creates.  An alternative solution is return the context make the view controller hold on to it until the it's finished with it.  This is probably a better solution because an app may have several prototypes that it creates, runs, and then destroys.  I think what's missing is a way to cleanup a context.  We probably also want to have some sort of facade so that people are doing stuff with the context directly.  Thoughts?

**Comment by andymatuschak** [comment]
Sorry about that—this particular target was meant as really barebones testbed, to be eventually superseded by OhaiPrototope (for Swift) and Protoscope (for JS). Not quite there yet.

Your intuition about having the VC own the `Context` is right.

**Comment by kevinb7** [comment]
I haven't done a lot of Swift programming so it's nice to know I'm not all thumbs.
