### ISSUE TITLE
Root layer touchesHandlers don't get called

### ISSUE THREAD

**Issue by andymatuschak** [Khan/Prototope#37]
You can't install touch handlers (e.g. `touchBeganHandler`) on the root layer of a prototype because it's a "captured" non-Prototope-controlled view, which means its view isn't a `TouchForwardingImageView`. We'll need to add an extra layer of indirection

**Comment by jbrennan** [comment]
What if we made the the "root view" just be a hosting view and only add layers to it? So when you set the root view, we don't make `environment.rootLayer = Layer(wrappingView: rootView...)` but the root layer's view is instead added as a subview of the "root view."

The view just hosts the layer hierarchy, but is not the same as Layer.root's view.

**Comment by andymatuschak** [comment]
Yep, that's the extra layer of indirection we need!

**Comment by jbrennan** [comment]
Alright, I'll tackle this one.

**Comment by andymatuschak** [comment]
:heart:
