### ISSUE TITLE
Protocaster should try to reconnect to protoscope when it reappears

### ISSUE THREAD

**Issue by jbrennan** [Khan/Prototope#42]
95% of the time, I want Protocaster to just reconnect to the device/simulator when it comes back online.

Self-assigning for now, but feel free to take it from me if you're looking for something to chew on!

**Comment by andymatuschak** [comment]
Oh man that would be suhweet

Probably should be like a timeout or something—maybe if you haven't been connected to a device for 4 hours, don't auto-reconnect? I probably feel differently from you on this because I work in an office with other people using Prototope. :)

**Comment by jbrennan** [comment]
Yeah that's fair!

**Comment by jbrennan** [comment]
> Probably should be like a timeout or something—maybe if you haven't been connected to a device for 4 hours, don't auto-reconnect? I probably feel differently from you on this because I work in an office with other people using Prototope. :)

Do you still feel like this would be an issue? The way I’m imagining it, you can still select a different device. It just remembers whatever you last selected, if it sees it.

**Comment by andymatuschak** [comment]
Yes, but only a minor one. Often we share devices around the office, and this could lead to surprises where a prototype on someone’s device is “overwritten” when someone else opens Protocaster.

Alternately: LiveView has a check box that lets you choose whether to always connect to the current device when it appears. Maybe that’s a reasonable model.

**Comment by saniul** [comment]
> Alternately: LiveView has a check box that lets you choose whether to always connect to the current device when it appears. Maybe that’s a reasonable model.

Sounds reasonable
