### ISSUE TITLE
Allow Gestures to be recognized simultaneously

### ISSUE THREAD

**Issue by saniul** [Khan/Prototope#6]
We need to somehow expose `gestureRecognizer(shouldRecognizeSimultaneouslyWithGestureRecognizer:)` if we want to be able to recognize more than 1 `Gesture` at a time.

Any thoughts on how that should work? I’d be willing to write up a PR for this.

* Flag on `Gesture` - something like `allowSimultaneousRecognitionWithAllOtherGestures`
* Array of `Gestures` on `Gesture` - allow simultaneous recognition with these gestures
* ???

**Comment by andymatuschak** [comment]
Yes, thank you for pointing that out!

I'd probably suggest something like this to start:

```swift
protocol Gesture {
  var shouldRecognizeSimultaneouslyWithGesture: Gesture -> Bool
}
```

I appreciate your generous offer to write a PR! Please don't feel at all obliged. :)

**Comment by saniul** [comment]
Hm, just realized that to make this possible we’ll need a way to map a UIGestureRecognizer to a prototope GestureType.

**Comment by andymatuschak** [comment]
Yeah, would have to keep a private mapping table around for each Prototope gesture we create.

**Comment by saniul** [comment]
Implemented in https://github.com/Khan/Prototope/pull/7
