### ISSUE TITLE
ShapeLayer bridge not throwing exceptions for line cap typos

### ISSUE THREAD

**Issue by jbrennan** [Khan/Prototope#71]
I'd expect the following JS code to throw an exception:

```javascript
var fingerPath = new ShapeLayer()
// notice "lineCapStype" instead of "lineCapStyle"
fingerPath.lineCapStype = LineCapStyle.Round
```

Instead it doesn't throw. It just seems to disregard this line.

**Comment by andymatuschak** [comment]
I think we probably shouldn't fix this! I really like being able to treat objects as random key-bags in prototypes. :/

**Comment by spicyj** [comment]
I knew you were a JavaScripter at heart, @andymatuschak. :)

```js
const draggingLayers = new Set()
someLayer.touchBeganHandler = sequence => {
  draggingLayers.add(someLayer)
}
```
