### ISSUE TITLE
Protoscope crashes when you don't pass the right type into segments property

### ISSUE THREAD

**Issue by nefaurk** [Khan/Prototope#92]
The following code will cause Protoscope to crash on the device:

let polygon = new ShapeLayer()
polygon.segments = [new Point({x: 0, y: 0})]

It looks like segments expects an array of Segment objects, not Point objects. We should probably throw a Protonope instead of crashing.

**Comment by jbrennan** [comment]
Fixed by 131718f

**Comment by jbrennan** [comment]
We might also want to consider just *accepting* an array of `Point` objects too.
