### ISSUE TITLE
I can haz custom fonts?

### ISSUE THREAD

**Issue by nefaurk** [Khan/Prototope#94]
It appears that bundling a font in your Prototope folder doesn't allow you to use that custom font in your prototype.

**Comment by NachoSoto** [comment]
I think custom fonts need to be listed in the app's `plist`, so it might not be possible to load an arbitrary font at runtime.

**Comment by saniul** [comment]
There's this: http://stackoverflow.com/questions/14048549/how-to-dynamically-load-a-font-under-ios-for-real

Seems like it's doable.

**Comment by andymatuschak** [comment]
Weird! It won't let me assign you! But you have commit privileges here. Hmmmm

**Comment by andymatuschak** [comment]
Ooooops, forgot to add the group I made to the collaborators list here. :D
